### ISSUE TITLE
error when execute

### ISSUE THREAD

**Issue by weiyuchen** [slgobinath/pcap-processor#2]
hello, I clone your work and run the requirements locally, including "requirements.txt", but I got an error

**Comment by weiyuchen** [comment]
`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/g6/traffic-classify/pcap-processor/pcap_processor/__main__.py", line 62, in <module>
    main()
  File "/home/g6/traffic-classify/pcap-processor/pcap_processor/__main__.py", line 45, in main
    plugin_manager.load_plugins()
  File "/home/g6/traffic-classify/pcap-processor/pcap_processor/plugin_manager.py", line 34, in load_plugins
    importlib.import_module(package_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/g6/traffic-classify/pcap-processor/pcap_processor/plugins/grpc_sink.py", line 24, in <module>
    from pcap_processor.grpc import WisdomGrpcService_pb2_grpc
  File "/home/g6/traffic-classify/pcap-processor/pcap_processor/grpc/WisdomGrpcService_pb2_grpc.py", line 4, in <module>
    import WisdomGrpcService_pb2 as WisdomGrpcService__pb2
ImportError: No module named 'WisdomGrpcService_pb2'
`

**Comment by weiyuchen** [comment]
the command I run is 
`python3 -m pcap_processor --sink csv ../flow/joomla/joomlavs.pcap
`

**Comment by weiyuchen** [comment]
I had checked the `processor/pcap_processor/plugins/grpc_sink.py` and `processor/pcap_processor/grpc/WisdomGrpcService_pb2_grpc.py`, but I can't find the solution, thx a lot!

**Comment by weiyuchen** [comment]
It runs well in my ubuntu desktop, the error environment is a server system "ubuntu server", I saw the problem is wisdomGrpcService, so I wondered if it needs desktop environment

**Comment by slgobinath** [comment]
Hi,
Please run the `build_grpc.sh` script first to create the RPC files. Those RPC files are included as a dependency to use `pcap-processor` with [Wisdom](https://slgobinath.github.io/wisdom/) stream processor.

**Comment by weiyuchen** [comment]
actually, I had run the script before I use pcap_processor, but it didn't create RPC file, is this the problem with my environment?

**Comment by usake** [comment]
I think the number of features is few

**Comment by sirwez** [comment]
i have problems in install requeriments, error 404 url not found for apt-clone and outers installs
